### ISSUE TITLE
Python generates the __hash__ function incorrectly

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/frugal#965]
## ULTIMATE PROBLEM:

When given a struct that contains sets, lists, and maps, frugal will incorrectly generate the corresponding __hash__ function for the struct. 

**Example:**

```thrift
 struct BadHashDTO {
    1: set<string> setType
    2: map<string> mapType
    3: list<string> listType 
    4: string normalType
}
```

Generates the following __hash__ function:

```python
 def __hash__(self):
        value = 17
        value = (value * 31) ^ hash(self.setType)
        value = (value * 31) ^ hash(self.mapType)
        value = (value * 31) ^ hash(self.listType)
        value = (value * 31) ^ hash(self.normalType)
        return value
```

The issue with this is that in python calling hash on the list, set, and map types yields the following errors:

```python
>>> hash({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'

>>> hash(set())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'set'

>>> hash([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

A solution to this would be to instead generate the following hash:

```python
 def __hash__(self):
        value = 17
        value = (value * 31) ^ hash(frozenset(self.setType))
        value = (value * 31) ^ hash(frozendict(self.mapType))
        value = (value * 31) ^ hash(tuple(self.listType))
        value = (value * 31) ^ hash(self.normalType)
        return value
```

This will probably be a quick fix to this line https://github.com/Workiva/frugal/blob/master/compiler/generator/python/generator.go#L502

### Note:

Ticket created https://jira.atl.workiva.net/browse/INFENG-5119

**Comment by brianshannan-wf** [comment]
Resolved in https://github.com/Workiva/frugal/pull/967
